---

- name: Initial Playbook
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    netbox_url: http://192.168.100.24:8000
    netbox_token: b361e1bb6ec9c616e17dc65e61bfbeaf3f368833
  tasks:

  - name: Check that you can connect (GET) to a page and it returns a status 200
    ansible.builtin.uri:
      url: "{{ netbox_url }}"
  - name: Get Devices
    ansible.builtin.uri:
       url: "{{ netbox_url }}/api/dcim/devices"
       method: GET
       headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: 'application/json'
       return_content: yes
       body_format: json
       status_code: [200, 201]
       validate_certs: false
    register: netbox_devices
    run_once: yes

  - name: show devices 
    ansible.builtin.debug:
       msg: "{{netbox_devices}}"

         
